export { default as ContactView } from './ContactView.svelte'
export { default as HeroView } from './HeroView.svelte'
export { default as ProjectsView } from './ProjectsView.svelte'
export { default as SkillsView } from './SkillsView.svelte'
export { default as TimelineView } from './TimelineView.svelte'