# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - Build sources

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

env:
  node_version: 18.x
  pnpm_version: 7.x

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3

      - name: Setup pnpm ${{ env.pnpm_version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm_version }}

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: lint
        run: pnpm run lint
